source $ZDOTDIR/config/config.zsh
if [[ $TERM != dumb ]]; then
  source $ZDOTDIR/config/keybinds.zsh
  source $ZDOTDIR/config/completion.zsh
  source $ZDOTDIR/config/aliases.zsh

  ##
  # fd > find
  if command -v fd >/dev/null; then
    export FZF_DEFAULT_OPTS="--reverse --ansi"
    export FZF_DEFAULT_COMMAND="fd ."
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND="fd -t d . $HOME"
  fi

  eval "$(fasd --init auto)"

  eval "$(direnv hook zsh)"

  ## Auto-generated by my nix config
  # source $ZDOTDIR/extra.zshrc

  ##
  autoload -Uz compinit && compinit -u -d $ZSH_CACHE/zcompdump

  # If you have host-local configuration, this is where you'd put it
  [ -f ~/.zshrc ] && source ~/.zshrc
fi
