source $ZDOTDIR/config/config.zsh
if [[ $TERM != dumb ]]; then
  source $ZDOTDIR/config/keybinds.zsh
  source $ZDOTDIR/config/completion.zsh
  source $ZDOTDIR/config/aliases.zsh

  # If you have host-local configuration, this is where you'd put it
  [ -f ~/.zshrc ] && source ~/.zshrc
fi
