[
  ./core
  ./db/postgres
  ./develop
  ./develop/kakoune
  ./develop/neovim
  ./develop/tmux
  ./develop/zsh
  ./graphical
  ./graphical/games
  ./graphical/im
  ./graphical/plex.nix
  ./graphical/sway
  ./laptop
  ./misc/disable-mitigations.nix
  ./misc/yubikey.nix
  ./network
  ./network/adblocking.nix
  ./network/stubby.nix
  ./network/torrent.nix
  ./ssh
]
